### ISSUE TITLE
#ДЗ JdbcTemplate + мультимодульный проект Maven

### ISSUE THREAD

**Issue by RenatFaiz** [RenatFaiz/MultiModuleApp#1]
@coursar Добрый день, Ильназ. Я создал [библиотеку jdbc-template](https://github.com/RenatFaiz/jdbc-template)  для подключения в виде зависимости.  Локально всё работает. Но Travis CI не может сделать сборку. Как я понимаю, причина  в отсутствии у него авторизации в GitHub packages. Как это исправить?
https://travis-ci.com/RenatFaiz/MultiModuleApp/builds/138036443

**Comment by coursar** [comment]
Вам нужно было просто сделать мультимодульный проект (где ваша библиотека jdbc-template) является одним из подмодулей.

Тогда бы Travis'у не пришлось ничего делать. Лучше сделать так.

А так нужно сделать следующее:
- создать в репозитории каталог .m2, куда положить файл settings.xml (аналогичный вашему локальному, но вместо захардкоженного access token прописать ${evn.GITHUB_TOKEN}
- поменять команду сборки Travis на mvn -s ./.m2/settings.xml -e mvn verify
- в переменные окружения Travis под именем GITHUB_TOKEN положить ваш access token.
