### ISSUE TITLE
ДЗ JdbcTemplate + мультимодульный проект Maven

### ISSUE THREAD

**Issue by RenatFaiz** [RenatFaiz/MultiModuleApp#2]
@coursar Добрый день!
Не могу задеплоить проект. Выдаёт ошибку 422 :
Заново генерировал новый токен 2 раза, не помогло.

> Failed to transfer file https://maven.pkg.github.com/RenatFaiz/MultiModuleApp/ru/itpark/multi-module-app/1.0/multi-module-app-1.0.pom with status code 422

Лог idea 
https://drive.google.com/open?id=1oyuwrZ01UmIEvFCA9HYpiW2WAQJJgFYU

ответ github (в браузере) -  
https://drive.google.com/open?id=19xiBmlAdAcjO1GFCODqK-6Nv39icoq2R

в Travis CI сборка проходит (значок на success не обновился пока что..))

**Comment by coursar** [comment]
1. Артефакт должен быть уникальным в рамках всего вашего Github аккаунта (а у вас уже есть jdbc-template тут: https://github.com/RenatFaiz/jdbc-template/packages)
2. Вы неправильно выстроили зависимости между модулями (jdbc-template ничего не должен знать про бизнес-логику)
3. Кроме того, в родительском pom'ник объявляются версии зависимостей, а не сами зависимости, пересмотрите видео.

**Comment by RenatFaiz** [comment]
Спасибо большое, Ильназ! Про уникальность пакета я, конечно, не подумал..)
А в родительском pom'е я добавил зависимость, чтобы создать класс Main и
протестировать работу программы. Видимо, надо это делать по-другому)

вс, 15 дек. 2019 г. в 10:19, coursar <notifications@github.com>:
